# Generated by Django 4.1 on 2023-10-11 23:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('ced', models.TextField(max_length=12, unique=True)),
                ('contrasena', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('ced', models.TextField(max_length=12)),
                ('tel', models.TextField(max_length=10)),
                ('nombre', models.TextField(max_length=50)),
                ('contrasena', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ManyToManyField(to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('precio', models.BigIntegerField()),
                ('descripcion', models.TextField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ciudad', models.TextField(max_length=20)),
                ('dir', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.ManyToManyField(to='api.oferta')),
                ('producto', models.ManyToManyField(to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unids', models.PositiveIntegerField()),
                ('color', models.ManyToManyField(to='api.color')),
                ('producto', models.ManyToManyField(to='api.producto')),
                ('talla', models.ManyToManyField(to='api.talla')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unids', models.PositiveIntegerField()),
                ('precio', models.PositiveBigIntegerField()),
                ('factura', models.ManyToManyField(to='api.factura')),
                ('producto', models.ManyToManyField(to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.ManyToManyField(to='api.venta'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.cliente')),
                ('unids', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('cliente', 'producto')},
            },
        ),
    ]
