# Generated by Django 4.1 on 2023-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_carrito_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_producto',
            name='color',
            field=models.ManyToManyField(to='api.color'),
        ),
        migrations.AddField(
            model_name='factura_producto',
            name='talla',
            field=models.ManyToManyField(to='api.talla'),
        ),
    ]
