name: Deployment

on:
  release:
    types: [published]

jobs:
  backend_deployment:
    name: Deploying backend to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.BACK_REP }}:latest, ${{ secrets.BACK_REP }}:${{ github.ref_name }}
          labels: backend

      - name: Deploy to production
        run: curl --request GET \ --url ${{ secrets.RENDER_BACK }}

  frontend_deployment:
    name: Deploying frontend to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontkend/Dockerfile
          push: true
          tags: ${{ secrets.FRONT_REP }}:latest, ${{ secrets.FRONT_REP }}:${{ github.ref_name }}
          labels: frontend

      - name: Deploy to production
        run: curl --request GET \ --url ${{ secrets.RENDER_FRONT }}
