name: Run tests
on:
  pull_request:
    branches:
    - develop

jobs:
  run-tests:
    if: ${{ github.event.sender.login == 'Criser2013' || github.event.sender.login == 'jesusGomezCadena'  || github.event.sender.login == 'SuescunJhon' }}
    name: Run Django tests
    runs-on: ubuntu-latest
    container:
      image: python:3.11.6-alpine
      volumes:
        - ${{ github.workspace  }}:/app
    services:
      postgres:
        image: postgres:16.0-alpine3.18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pg123
          POSTGRES_DB: testing
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Installing dependencies
        run: pip install -r ./backend/requirements.txt

      - name: Running tests
        env:
          SECRET_KEY: ${{ secrets.SECRETKEY }}
          POSTGRES_NAME: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pg123
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDAPIKEY }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDNAME }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDAPISECRET }}
        run: |
            cd backend
            python manage.py test

  react-test:
    if: ${{ github.event.sender.login == 'DanielFRoseroZ' || github.event.sender.login == 'Hickaro12' }}
    name: Run React tests
    runs-on: ubuntu-latest
    container:
      image: 'node:18-alpine3.18'
      volumes:
        - ${{ github.workspace  }}:/app
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Running tests
      run: npm test